# Animation size
CANVAS_HEIGHT = 800
CANVAS_WIDTH  = 800

# number of frames
TOTAL_FRAMES  = 200
SECS_PER_LOOP = 0.5
ANIMATION_SPEEDUP = 25.0

# Cost function constants
ILLEGAL_COST = 100
DANGEROUS_COST = 1

# speeds
SLOW = 20 # slow lane
FAST = 30 # fast lane
SPEED_LIMIT = 40

MAX_ACC = 9.8

LANE_CHANGE_WEIGHT = 0.2
VELOCITY_WEIGHT    = 2.0
GAP_SIZE_WEIGHT    = 0.2

DESIRED_CAR_LENGTH_SEPARATION = 5

TRACK_RADIUS = 300
NUM_LANES = 2
LANE_WIDTH = 20

CARS_PER_LANE = [ 6, 2]

LOCALIZATION_UPDATE_RATE = 1
BEHAVIOR_UPDATE_RATE     = 2
PREDICTION_UPDATE_RATE   = 40

ACTOR_DATA_FILE_NAME = "output.json"

GOAL = (1205.0, 0)

INITIAL_EGO_POSE = (805.0, 1, 1)